version: "3"
services:
    focalboard:
        stdin_open: true
        tty: true
        ports:
            - 8000:8000
        image: mattermost/focalboard
        volumes:
            - focalboard_data:/opt/focalboard/data

# Ezeket a volume-okat előre létrekell hozni:
# docker volume create focalboard_data
volumes:
  focalboard_data:
    external: true