name: bookstack
services:
    bookstack:
        image: lscr.io/linuxserver/bookstack
        container_name: bookstack
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
            - APP_URL=http://localhost:8000
            - DB_HOST=database
            - DB_PORT=3306
            - DB_USER=bookstack
            - DB_PASS=1234pass
            - DB_DATABASE=bookstackapp
        volumes:
            - server_volume:/config
        ports:
            - 8000:80
        restart: unless-stopped
        depends_on:
            - database
        networks:
            - bookstack_network
    database:
        image: lscr.io/linuxserver/mariadb
        container_name: database
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
            - MYSQL_ROOT_PASSWORD=1234pass
            - MYSQL_DATABASE=bookstackapp
            - MYSQL_USER=bookstack
            - MYSQL_PASSWORD=1234pass
        volumes:
            - database_volume:/config
        restart: unless-stopped
        networks:
            - bookstack_network
networks:
    bookstack_network:
        name: bookstack_network
        external: false
volumes:
    server_volume:
        external: false
    database_volume:
        external: false