# Ezeket a volume-okat előre létrekell hozni:
# docker volume create corteza_server
# docker volume create corteza_database
name: corteza_container
services:
    corteza_server:
        image: cortezaproject/corteza:${VERSION}
        restart: always
        env_file:
            - .env
        depends_on:
            - corteza_database
        ports:
            - 8100:80
        volumes:
            - corteza_server_data:/data
    corteza_database:
        # PostgreSQL Database
        # See https://hub.docker.com/_/postgres for details
        # Support for postgres 13, 14 and 15 is available in the latest version of Corteza
        image: postgres:15
        restart: always
        healthcheck:
            test:
                - CMD-SHELL
                - pg_isready -U corteza
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - corteza_db_data:/var/lib/postgresql/data
        environment:
            # Warning: these are values that are only used on 1st start
            # if you want to change it later, you need to do that
            # manually inside corteza_database container
            POSTGRES_USER: corteza
            POSTGRES_PASSWORD: corteza
volumes:
    corteza_server:
        external: true
    corteza_database:
        external: true