name: joget
services:
    joget:
        ports:
            - 8500:8080
        volumes:
            - mysql_volume:/var/lib/mysql
            - workflow_volume:/opt/joget/wflow
        container_name: joget
        image: jogetworkflow/joget-community
        networks:
            - joget_network
networks:
    joget_network:
        name: joget_network
        external: false
volumes:
  mysql_volume:
    external: false
  workflow_volume:
    external: false