---
version: "3"
services:
    openproject:
        stdin_open: true
        tty: true
        ports:
            - 8080:80
        environment:
            - OPENPROJECT_SECRET_KEY_BASE=secret
            - OPENPROJECT_HOST__NAME=localhost:8080
            - OPENPROJECT_HTTPS=false
            - OPENPROJECT_DEFAULT__LANGUAGE=en
        image: openproject/openproject:14
        volumes:
            - openproject_assets:/var/openproject/assets
            - openproject_pgdata:/var/openproject/pgdata

# Ezeket a volume-okat előre létrekell hozni:
# docker volume create openproject_assets
# docker volume create openproject_pgdata
volumes:
  openproject_assets:
    external: true
  openproject_pgdata:
    external: true