name: openproject
services:
    openproject:
        stdin_open: true
        tty: true
        ports:
            - 9400:80
        environment:
            - OPENPROJECT_SECRET_KEY_BASE=secret
            - OPENPROJECT_HOST__NAME=localhost:9400
            - OPENPROJECT_HTTPS=false
            - OPENPROJECT_DEFAULT__LANGUAGE=en
        image: openproject/openproject:14
        container_name: openproject
        volumes:
            - assets_volume:/var/openproject/assets
            - pgdata_volume:/var/openproject/pgdata
        networks:
            - openproject_network
networks:
    openproject_network:
        name: openproject_network
        external: false
volumes:
    assets_volume:
        external: false
    pgdata_volume:
        external: false