name: karavan
services:
    server:
        env_file:
            - .env
        container_name: server
        image: ghcr.io/apache/camel-karavan:4.5.1
        ports:
            - 8300:8080
        environment:
            - KARAVAN_GIT_REPOSITORY=${KARAVAN_GIT_REPOSITORY}
            - KARAVAN_GIT_USERNAME=${KARAVAN_GIT_USERNAME}
            - KARAVAN_GIT_PASSWORD=${KARAVAN_GIT_PASSWORD}
            - KARAVAN_GIT_BRANCH=main
            - KARAVAN_CONTAINER_IMAGE_REGISTRY=registry:5000
            - KARAVAN_CONTAINER_IMAGE_REGISTRY_USERNAME=
            - KARAVAN_CONTAINER_IMAGE_REGISTRY_PASSWORD=
            - KARAVAN_CONTAINER_IMAGE_GROUP=karavan
            - KARAVAN_DOCKER_NETWORK=karavan
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - org.apache.camel.karavan/type=internal
        networks:
            - karavan_network
    registry:
        container_name: registry
        image: registry:2
        restart: always
        ports:
            - 8355:5000
        labels:
            - org.apache.camel.karavan/type=internal
        networks:
            - karavan_network
        volumes:
            - registry_volume:/var/lib/registry
networks:
    karavan_network:
        name: karavan_network
        external: false
volumes:
    registry_volume:
        external: false