# ignored options for 'all-in-one'
# --sig-proxy=false
name: nc-aio
services:
    all-in-one:
        init: true
        container_name: nextcloud-aio-mastercontainer
        restart: always
        ports:
            - 9997:80
            - 9998:8080
            - 9999:8443
        volumes:
            - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
            - /var/run/docker.sock:/var/run/docker.sock:ro
        image: nextcloud/all-in-one:latest
volumes:
    nextcloud_aio_mastercontainer:
        external: false
        name: nextcloud_aio_mastercontainer